name:                aoc
version:             0.1.0.0
github:              "amar-laksh/aoc"
license:             BSD3
author:              "Amar Lakshya"
maintainer:          "example@example.com"
copyright:           "2022 Amar Lakshya"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/amar-laksh/aoc#readme>

dependencies:
- base >= 4.7 && < 5
- process

library:
  source-dirs: src

executables:
  aoc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    - -Werror
    - -Wno-type-defaults

    dependencies:
    - aoc

tests:
  aoc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    default-extensions:
    - ScopedTypeVariables
    dependencies:
    - aoc
    - tasty
    - tasty-hunit
    - tasty-smallcheck
    - silently
    - smallcheck

benchmarks:
  aoc-bench:
    main: Bench.hs
    source-dirs: bench
    default-extensions:
    - ScopedTypeVariables

    ghc-options:
    - -threaded
    - -rtsopts
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    - -Werror
    - -Wno-type-defaults

    dependencies:
    - silently
    - aoc
    - tasty-bench
    - tasty-smallcheck


